feat: добавить объекты user, item и repositories, services, controllers к ним
DenisPolo/java-shareit pull request #1
Opened 2023-07-29 15:06 UTC by DenisPolo

Создана основа для приложения по аренде вещей, добавлены объекты user, item и repositories, services, controllers к ним

2023-07-29 20:26 UTC, andrew-larkin requested changes
Привет! Отличный старт, структура выполнена корректно, код достаточно чистый и без особых нареканий. Буквально в паре мест поправить и будем готовы двигаться дальше.

2023-07-29 20:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> findItems(@RequestHeader(name = "X-Sharer-User-Id", required = false) Long userId) {
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.service.findAllItems());
Для всех методов во всех контроллерах стоит его добавить

2023-07-29 20:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            return service.findAllItems();
эту конструкцию с выбором нужного метода лучше перенести в сервис

2023-07-30 06:44 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> findItems(@RequestHeader(name = "X-Sharer-User-Id", required = false) Long userId) {
Добавил ResponseEntity во все методы контроллеров ItemController и UserController

2023-07-30 06:45 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            return service.findAllItems();
Перенес выбор метода в сервис

2023-08-01 01:43 UTC, merged