feat: добавить базу данных и бронирование
DenisPolo/java-shareit pull request #2
Opened 2023-08-21 03:11 UTC by DenisPolo

Добавлен функционал бронирования и база данных

2023-08-21 16:26 UTC, andrew-larkin requested changes
Привет! Отличная работа, реализация новых сервисов на очень хорошем уровне - архитектурно и по чистоте кода. Остается внести небольшие корректировки (я написал комменты в одно экземпляре, но они актуальны для всех схожих ситуаций) и будем готовы двигаться дальше.

2023-08-21 16:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
в моделях лучше не использовать @Data - она может некорректно рассчитывать хэш. Можно использовать @Getter, @Setter и т.п.

2023-08-21 16:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        QueryState queryState = Enum.valueOf(QueryState.class, state);
строку с вычислением стейта лучше перенести в сервис, чтобы тут остался только вызов метода сервиса, а контроллер выполнял только одну функцию - маршрутизацию запросов

2023-08-21 16:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
для этого приложения давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Все методы маппинга будут писаться в одну строчку благодаря ней, и нам это очень облегчит работу над этим приложением в ближайших спринтах

2023-08-21 16:26 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
@Repository над репозиториями следует добавить

2023-08-21 16:26 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#logging.level.org.springframework.orm.jpa=INFO
закомментированные настройки удаляем

2023-08-21 16:26 UTC, andrew-larkin commented on src/main/resources/schema.sql
> +--DROP TABLE IF EXISTS PUBLIC.users CASCADE;
здесь тоже удаляем

2023-08-23 08:10 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Заменил @Data на @Getter и @Setter, также кое-где переопределил equals и hashCode

2023-08-23 08:12 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
Добавил mapStruct, только один метод при формировании ItemWithBookingsDto сделал default, т.к. не нашел более подходящего решения

2023-08-23 08:12 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        QueryState queryState = Enum.valueOf(QueryState.class, state);
Перенёс

2023-08-23 08:13 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
Добавил

2023-08-23 08:13 UTC, DenisPolo commented on src/main/resources/application.properties
> +#logging.level.org.springframework.orm.jpa=INFO
Удалил всё лишнее

2023-08-26 03:47 UTC, merged