feat: добавить item requests, тесты
DenisPolo/java-shareit pull request #3
Opened 2023-09-12 09:37 UTC by DenisPolo

Добавить функциональность item requests и тесты

2023-09-14 16:16 UTC, andrew-larkin requested changes
Привет! Реализация просто отличные, и покрытие тестами и сами тесты на очень высоком уровне! Уже чувствуется опыт. По идее, после окончания работы над этим приложением, можно уже активно начинать поиск работы. А сейчас остается внести буквально пару правок и будем готовы приступать к финальному этапу для этого приложения.

2023-09-14 16:16 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/comment/model/Comment.java
> +@AllArgsConstructor
в 34-й строке itemId нужно заменить на соответствующий класс и установить связь между объектами

2023-09-14 16:16 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
здесь должен быть соответствующий класс и установлена связь между объектами (как в строке 27)

2023-09-14 16:16 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private Long userId;
здесь должен быть класс User и настроена соответствующая связь между классами

2023-09-16 06:16 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/item/comment/model/Comment.java
> +@AllArgsConstructor
Заменил

2023-09-16 06:18 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
Также заменил

2023-09-16 06:18 UTC, DenisPolo commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private Long userId;
И здесь поправил

2023-09-17 04:14 UTC, merged