Добавить микросервисную архитектуру
DenisPolo/java-shareit pull request #4
Opened 2023-10-08 11:40 UTC by DenisPolo

Разбить приложение на микросервисы gateway и server

2023-10-08 17:32 UTC, andrew-larkin requested changes
Привет! Отлично, приложение без проблем запускается в докере, а новый функицонал для gateway реализован очень качественно, уже чувствуется опыт) Остается немного донастроить docker-compose и приложение будет полностью готово.

2023-10-08 17:32 UTC, andrew-larkin commented on docker-compose.yml
> +    container_name: shareit-gateway
для сервисов стоит еще добавить настройку restart on failure

2023-10-08 17:32 UTC, andrew-larkin commented on docker-compose.yml
> +    ports:
для БД еще стоит настроить volumes

2023-10-08 17:32 UTC, andrew-larkin commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
закомментированый код везде удаляем

2023-10-10 15:11 UTC, DenisPolo commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Удалил

2023-10-10 15:12 UTC, DenisPolo commented on docker-compose.yml
> +    ports:
volumes настроен, после удаления контейнера и создания нового в базе данные сохранены

2023-10-10 15:12 UTC, DenisPolo commented on docker-compose.yml
> +    container_name: shareit-gateway
добавил

2024-01-17 00:15 UTC, merged